### ISSUE TITLE
qr code library fails to render string

### ISSUE THREAD

**Issue by susmit** [thecryptobee/MyMoneyApp#16]
QR code library used in app fails to render qrcode if string is between length 192 and 220.It is a bug in library side.Support link [https://stackoverflow.com/questions/30796584/qrcode-js-error-code-length-overflow-17161056](https://stackoverflow.com/questions/30796584/qrcode-js-error-code-length-overflow-17161056)

**Comment by Varunram** [comment]
closing since we're archiving the repo
